### ISSUE TITLE
Habanero PCIe direct slots - won't train

### ISSUE THREAD

**Issue by brs332** [open-power/hostboot-targeting#7]
Adapters in direct PCIe slots (ie. both white slotted connectors) won't train. 

(Please put network adapters in slot behind the PLX switch.)

**Comment by vongvibool** [comment]
This is still working for me on hab3 using 
(Buildroot 2014.08-git-g0c1bab4) ) #54 SMP Mon Nov 24 09:13:52 CST 2014

Will try loop testing or something.

/ # lspci
0000:00:00.0 PCI bridge: IBM Device 03dc
0000:01:00.0 Ethernet controller: Mellanox Technologies MT27500 Family [ConnectX-3]
0001:00:00.0 PCI bridge: IBM Device 03dc
0001:01:00.0 PCI bridge: PLX Technology, Inc. Device 8748 (rev ca)
0001:02:01.0 PCI bridge: PLX Technology, Inc. Device 8748 (rev ca)
0001:02:02.0 PCI bridge: PLX Technology, Inc. Device 8748 (rev ca)
0001:02:08.0 PCI bridge: PLX Technology, Inc. Device 8748 (rev ca)
0001:02:09.0 PCI bridge: PLX Technology, Inc. Device 8748 (rev ca)
0001:02:0a.0 PCI bridge: PLX Technology, Inc. Device 8748 (rev ca)
0001:02:10.0 PCI bridge: PLX Technology, Inc. Device 8748 (rev ca)
0001:02:11.0 PCI bridge: PLX Technology, Inc. Device 8748 (rev ca)
0001:03:00.0 Ethernet controller: Mellanox Technologies MT27520 Family [ConnectX-3 Pro]
0001:04:00.0 Ethernet controller: Mellanox Technologies MT27520 Family [ConnectX-3 Pro]
0001:05:00.0 SATA controller: Marvell Technology Group Ltd. Device 9235 (rev 11)
0001:06:00.0 USB controller: Texas Instruments TUSB73x0 SuperSpeed USB 3.0 xHCI Host Controller (rev 02)
0001:07:00.0 PCI bridge: ASPEED Technology, Inc. AST1150 PCI-to-PCI Bridge (rev 03)
0001:08:00.0 VGA compatible controller: ASPEED Technology, Inc. ASPEED Graphics Family (rev 30)
0002:00:00.0 PCI bridge: IBM Device 03dc
0002:01:00.0 Ethernet controller: Intel Corporation 82571EB Gigabit Ethernet Controller (rev 06)
0002:01:00.1 Ethernet controller: Intel Corporation 82571EB Gigabit Ethernet Controller (rev 06)

**Comment by vongvibool** [comment]
On hab03 found the problem exists with x4 or x1 pcie adapters only and the problem is due to lane reversal settings on the x8 direct slot.  If you get a chance could you verify a x8 adapter shows up in both slots.

**Comment by brs332** [comment]
@bwmashak noted this should be closed.
